"""当前文本事实契约 的 Python 适配层公开入口。"""

from app.text_fact_core import TextFactContractError, read_current_text_fact_scope
from app.text_fact_counts import (
    count_current_text_facts,
    count_pending_text_fact_quality_errors_by_type,
    count_pending_text_fact_quality_errors,
    count_pending_text_facts,
    count_rule_hit_text_facts,
    count_stale_translations_outside_writable_text_facts,
    count_translated_text_facts,
    count_writable_text_facts,
    read_pending_text_fact_quality_error_fact_ids,
    read_pending_text_fact_quality_error_paths,
    read_text_fact_quality_error_fact_ids,
    read_text_fact_quality_error_paths,
)
from app.text_fact_quality import (
    read_text_fact_quality_items_for_translations,
    read_text_fact_sample_details_by_fact_ids,
    read_text_fact_sample_details_by_paths,
    text_fact_record_to_quality_item,
    text_fact_record_to_translation_item,
    text_fact_records_to_translation_data_map,
)
from app.text_fact_readers import (
    read_current_text_fact_placeholder_entries,
    read_current_text_fact_records,
    read_current_text_fact_translation_data_map,
    read_current_text_fact_translation_items_by_paths,
    read_pending_text_fact_path_samples,
    read_pending_text_fact_records,
    read_pending_text_fact_translation_data_map,
    read_pending_text_fact_translation_items,
    read_stale_translation_path_samples_outside_writable_text_facts,
    read_unwritable_text_fact_records,
    read_writable_text_fact_translation_items_by_fact_ids,
    read_writable_text_fact_translation_items_by_paths,
    read_writable_text_fact_translation_items,
)

__all__ = [
    "TextFactContractError",
    "count_current_text_facts",
    "count_pending_text_fact_quality_errors_by_type",
    "count_pending_text_fact_quality_errors",
    "count_pending_text_facts",
    "count_rule_hit_text_facts",
    "count_stale_translations_outside_writable_text_facts",
    "count_translated_text_facts",
    "count_writable_text_facts",
    "read_current_text_fact_placeholder_entries",
    "read_current_text_fact_records",
    "read_current_text_fact_scope",
    "read_current_text_fact_translation_data_map",
    "read_current_text_fact_translation_items_by_paths",
    "read_pending_text_fact_path_samples",
    "read_pending_text_fact_quality_error_fact_ids",
    "read_pending_text_fact_quality_error_paths",
    "read_pending_text_fact_records",
    "read_pending_text_fact_translation_data_map",
    "read_pending_text_fact_translation_items",
    "read_stale_translation_path_samples_outside_writable_text_facts",
    "read_text_fact_quality_error_fact_ids",
    "read_text_fact_quality_error_paths",
    "read_text_fact_quality_items_for_translations",
    "read_text_fact_sample_details_by_fact_ids",
    "read_text_fact_sample_details_by_paths",
    "read_unwritable_text_fact_records",
    "read_writable_text_fact_translation_items_by_fact_ids",
    "read_writable_text_fact_translation_items_by_paths",
    "read_writable_text_fact_translation_items",
    "text_fact_record_to_quality_item",
    "text_fact_record_to_translation_item",
    "text_fact_records_to_translation_data_map",
]
