"""Text Fact Contract v2 的 Python 适配层公开入口。"""

from app.text_fact_core import TextFactContractError, read_current_text_fact_scope_v2
from app.text_fact_counts import (
    count_current_text_facts_v2,
    count_pending_text_fact_quality_errors_by_type_v2,
    count_pending_text_fact_quality_errors_v2,
    count_pending_text_facts_v2,
    count_rule_hit_text_facts_v2,
    count_stale_translations_outside_writable_text_facts_v2,
    count_translated_text_facts_v2,
    count_writable_text_facts_v2,
    read_pending_text_fact_quality_error_fact_ids_v2,
    read_pending_text_fact_quality_error_paths_v2,
    read_text_fact_quality_error_fact_ids_v2,
    read_text_fact_quality_error_paths_v2,
)
from app.text_fact_quality import (
    read_text_fact_quality_items_for_translations,
    read_text_fact_sample_details_by_fact_ids_v2,
    read_text_fact_sample_details_by_paths_v2,
    text_fact_record_to_quality_item,
    text_fact_record_to_translation_item,
    text_fact_records_to_translation_data_map,
)
from app.text_fact_readers import (
    read_current_text_fact_placeholder_entries_v2,
    read_current_text_fact_records_v2,
    read_current_text_fact_translation_data_map_v2,
    read_current_text_fact_translation_items_by_paths,
    read_pending_text_fact_path_samples_v2,
    read_pending_text_fact_records_v2,
    read_pending_text_fact_translation_data_map,
    read_pending_text_fact_translation_items,
    read_stale_translation_path_samples_outside_writable_text_facts_v2,
    read_unwritable_text_fact_records_v2,
    read_writable_text_fact_translation_items_by_fact_ids,
    read_writable_text_fact_translation_items_by_paths,
    read_writable_text_fact_translation_items_v2,
)

__all__ = [
    "TextFactContractError",
    "count_current_text_facts_v2",
    "count_pending_text_fact_quality_errors_by_type_v2",
    "count_pending_text_fact_quality_errors_v2",
    "count_pending_text_facts_v2",
    "count_rule_hit_text_facts_v2",
    "count_stale_translations_outside_writable_text_facts_v2",
    "count_translated_text_facts_v2",
    "count_writable_text_facts_v2",
    "read_current_text_fact_placeholder_entries_v2",
    "read_current_text_fact_records_v2",
    "read_current_text_fact_scope_v2",
    "read_current_text_fact_translation_data_map_v2",
    "read_current_text_fact_translation_items_by_paths",
    "read_pending_text_fact_path_samples_v2",
    "read_pending_text_fact_quality_error_fact_ids_v2",
    "read_pending_text_fact_quality_error_paths_v2",
    "read_pending_text_fact_records_v2",
    "read_pending_text_fact_translation_data_map",
    "read_pending_text_fact_translation_items",
    "read_stale_translation_path_samples_outside_writable_text_facts_v2",
    "read_text_fact_quality_error_fact_ids_v2",
    "read_text_fact_quality_error_paths_v2",
    "read_text_fact_quality_items_for_translations",
    "read_text_fact_sample_details_by_fact_ids_v2",
    "read_text_fact_sample_details_by_paths_v2",
    "read_unwritable_text_fact_records_v2",
    "read_writable_text_fact_translation_items_by_fact_ids",
    "read_writable_text_fact_translation_items_by_paths",
    "read_writable_text_fact_translation_items_v2",
    "text_fact_record_to_quality_item",
    "text_fact_record_to_translation_item",
    "text_fact_records_to_translation_data_map",
]
